"""Code generation for contracts, and the check that generated files are up to date.

``render_tables`` writes one constant per table (``EVENTS_CLEAN = TableContract(...)``) so tables are
referenced by symbol. ``render_ontology`` runs LinkML's Pydantic and JSON Schema generators. Output is
deterministic, so ``dataplat contracts check`` can compare regenerated text with the committed file.
"""

from __future__ import annotations

import re
from collections.abc import Sequence
from dataclasses import dataclass
from pathlib import Path

from dataplat.contracts.model import TableContract

HEADER = (
    '"""GENERATED by `dataplat contracts gen` from {source}.\n\n'
    "Do not edit. Change the LinkML file and run `just contracts`; CI fails when this file is stale.\n"
    '"""\n\n'
    "from dataplat.contracts import Column, TableContract\n"
)


def const_name(class_name: str) -> str:
    return re.sub(r"(?<!^)(?=[A-Z])", "_", class_name).upper()


def _lit(v: object) -> str:
    return repr(v)


def _column(c: object) -> str:
    fields = [f"name={_lit(c.name)}", f"dtype={_lit(c.dtype)}"]  # type: ignore[attr-defined]
    for attr, default in (
        ("required", False),
        ("pattern", None),
        ("allowed", None),
        ("minimum", None),
        ("maximum", None),
        ("description", ""),
    ):
        val = getattr(c, attr)
        if val != default:
            fields.append(f"{attr}={_lit(val)}")
    return "        Column(" + ", ".join(fields) + "),\n"


def render_tables(contracts: Sequence[TableContract], source: str) -> str:
    out = [HEADER.format(source=source)]
    names = []
    for t in sorted(contracts, key=lambda c: c.name):
        n = const_name(t.name)
        names.append(n)
        out.append(f"\n{n} = TableContract(\n")
        out.append(f"    name={_lit(t.name)},\n    table={_lit(t.table)},\n")
        out.append("    columns=(\n")
        out.extend(_column(c) for c in t.columns)
        out.append("    ),\n")
        for attr, default in (
            ("partition_by", None),
            ("grain", ()),
            ("cadence", None),
            ("expected_start", None),
            ("description", ""),
        ):
            val = getattr(t, attr)
            if val != default:
                out.append(f"    {attr}={_lit(val)},\n")
        out.append(")\n")
    members = "".join(f"{n}, " for n in names).rstrip(", ") + ("," if len(names) == 1 else "")
    out.append(f"\nALL: tuple[TableContract, ...] = ({members})\n")
    return "".join(out)


def render_ontology_pydantic(schema_path: Path) -> str:
    from linkml.generators.pydanticgen import PydanticGenerator

    return str(PydanticGenerator(str(schema_path)).serialize())


def render_ontology_jsonschema(schema_path: Path) -> str:
    from linkml.generators.jsonschemagen import JsonSchemaGenerator

    return str(JsonSchemaGenerator(str(schema_path)).serialize()) + "\n"


@dataclass(frozen=True)
class Output:
    path: Path
    text: str

    def stale(self) -> bool:
        return not self.path.is_file() or self.path.read_text() != self.text

    def write(self) -> None:
        self.path.parent.mkdir(parents=True, exist_ok=True)
        init = self.path.parent / "__init__.py"
        if self.path.suffix == ".py" and not init.exists():
            init.write_text('"""Generated contracts. Do not edit."""\n')
        self.path.write_text(self.text)
